language: python
sudo: false
env:
  global:
    secure: "c4TpUlz4tasCncCPBJQnrA5CV1MOyRcdwoVW0bXU2tKkTY+3HubKkhv8JaaaOlSUWUwK1udJgadH6yowQskZTBgbUt35jxznyICzKKvxT+Bto7w9OLJlDSG4dLxD2yg6OygQ09+34b3fxe09SEJFfLVU3ktJ2PWzr2K/iWTpkW6CICtRbJiTNRRNqKcuOMQZkWZEpqO/q35m+DVyDI6QWplZIbyAj0p9vecPVmbYT7oROCBrSGte0Dd4tksEiEtxUe6/AZFxeAZqyyrI/8l5uGNk73KnntA7U53VNnO792jEuZ3eQpNHZpdgFRpocRbdBMZFToqH6GLYmD5iu7v93zV47WfKbIm2ods8PbVPOQOn1zMmVNpoCRfBUJYhZkLVPWGeJEM46wMRyLQw2uHFe2CIaHCmMQyueCpujGfvpxKfFkK2AZoQoiaRDs6O9vQSGfz3UdBSNmovws3waf+Mc2D/7vRGFBhqcicDJohPNaTOraCi0rEs+ioOpzD9z2QPfEdwwVcmMIx7CeNL83c4d13sEUJxVlj+SjsyUc2JEkYOWJrd7z6vnw8F875oaKMlFXTDcbPupeCZjjzn8VtRrXJ41ckvOWNJ6Cm78nXX5DbckPwDrQA2bMBBj3cs51yZt0J775qJoGCiPrmaHngeeKLEF11WxLV3fRy7tMLc5fs="
  matrix:
    - CUTTING_EDGE=true

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/matplotlib

services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

python:
  - 3.5
before_install:
  - git clone https://github.com/NSLS-II/nsls2-ci --branch master --single-branch ~/ci_scripts
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda update conda --yes
  - export CONDARC=ci/condarc
  - export MDS_HOST=localhost
  - export MDS_DATABASE=test
  - export MDS_TIMEZONE=US/Eastern
  - mkdir -p /home/travis/.config/metadatastore
  - 'echo ''port: 27017'' > /home/travis/.config/metadatastore/connection.yml'
  - export FS_HOST=localhost
  - export FS_DATABASE=test
  - mkdir -p /home/travis/.config/filestore
  - 'echo ''port: 27017'' > /home/travis/.config/filestore/connection.yml'


install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create --yes -n testenv numpy scipy flake8 matplotlib python=$TRAVIS_PYTHON_VERSION pytest coverage pip xlrd scikit-beam pyFAI pyxdameraulevenshtein -c conda-forge -c lightsource2-dev -c lightsource-tag -c lightsource2 -c soft-matter
  - source activate testenv
  - pip install https://github.com/NSLS-II/ophyd/zipball/master#egg=ophyd
  - pip install https://github.com/NSLS-II/event-model/zipball/master#egg=event_model
  - pip install https://github.com/NSLS-II/databroker/zipball/master#egg=databroker
  - pip install https://github.com/NSLS-II/bluesky/zipball/master#egg=bluesky
  - cp xpdan/config/xpdan.yml /home/travis/.config/xpdan.yml
  - pip install https://github.com/mrocklin/streamz/zipball/master#egg=streamz
  - pip install https://github.com/xpdAcq/SHED/zipball/master#egg=shed
  - pip install https://github.com/xpdAcq/xpdView/zipball/master#egg=xpdview
  - pip install https://github.com/xpdAcq/xpdSim/zipball/master#egg=xpdsim
  - pip install .
  - pip install codecov pytest-env

script:
  - set -e
  - coverage run run_tests.py
  - coverage report -m
  - flake8 xpdan
  - conda install --yes sphinx sphinx_rtd_theme
  - pip install git+git://github.com/drdoctr/doctr.git
  - cd docs
  - make html
  - cd ..
  - doctr deploy . --built-docs ./docs/_build/html;

after_success:
  - codecov
